us-east-1:
  build: .
  command: make
  environment:
    - AWS_REGION=us-east-1
    - ENV=dev
  log_driver: "awslogs"
  log_opt:
    awslogs-region: "us-east-1"
    awslogs-group: "dev-aws-services"

us-west-2:
  build: .
  command: make
  environment:
    - AWS_REGION=us-west-2
    - ENV=dev
  log_driver: "awslogs"
  log_opt:
    awslogs-region: "us-west-2"
    awslogs-group: "dev-aws-services"

jenkins:
  image: alexough/asjenkins
  ports:
    - "8080:8080"
  volumes:
    - /home/ec2-user/ebs_volume/jenkins:/var/jenkins_home

